#!/usr/bin/env bash
# script that will display information about subdomains.
if (($# == 2))
then
    echo -n "The subdomain $2 is a " ; dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4 " record and points to " $5}'
elif (($# == 1))
then
    echo -n "The subdomain www is a " ; dig "www.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4 " record and points to " $5}'
    echo -n "The subdomain lb-01 is a " ; dig "lb-01.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4 " record and points to " $5}'
    echo -n "The subdomain web-01 is a " ; dig "web-01.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4 " record and points to " $5}'
    echo -n "The subdomain web-02 is a " ; dig "web-02.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4 " record and points to " $5}'
fi
