#!/usr/bin/env bash
# Configure nginx to redirect to another page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sudo sed -i '/server_name _;/ a rewrite ^/redirect_me https://www.youtube.com/watch?v=ly_Ub9Lytk0 permanent;' /etc/nginx/sites-available/default
sudo service nginx start
