#!/usr/bin/env bash
# Script to configure a new server
sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw enable
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo sed -i "/server_name _;/ a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart
