#!/usr/bin/env bash
# Scrip to install nginx and make it listen on port 80
sudo apt-get remove -y --purge nginx nginx-common
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sed -i 's/8080/80/g' /etc/nginx/sities-enabled/default
sudo service nginx start
pkill -o nginx

