#!/usr/bin/env bash
# Install and configue ufw to block incomming traffic except 22, 443 and 80 tcp ports
sudo apt-get install ufw
sudo ufw default deny incomming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
